twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['./forms/theme.html.twig']
    globals:
        app_title: 'Boilerplate'

when@test:
    twig:
        strict_variables: true
