twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['./forms/theme.html.twig']
    globals:
        app_title: '%env(APP_TITLE)%'
        seo_title: '%env(SEO_TITLE)%'
        seo_description: '%env(SEO_DESCRIPTION)%'
        seo_link: '%env(SEO_LINK)%'

when@test:
    twig:
        strict_variables: true
